[package]
name = "rustwasmdemo1"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
# 尽量不引入会触发多表/引用类型的依赖，保持纯函数指针用法
